<a href="https://colab.research.google.com/github/iamchenchu/Deep-Learning-with-PyTorch/blob/main/Deep_Learning_PyTorch_Practice_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
print(torch.__version__)

2.2.1+cu121


In [ ]:
# Scalar
scalar = torch.Tensor(10)

print(scalar)
print(type(scalar))
print("shape is :", scalar.shape)
print("Dimention is :", scalar.ndim)
print("Size is :", scalar.size())


tensor([ 1.7803e+02,  3.2084e-41,  1.0959e+02,  3.2084e-41,  8.9683e-44,
         0.0000e+00,  1.3452e-43,  0.0000e+00, -4.2714e-25,  7.0065e-45])
<class 'torch.Tensor'>
shape is : torch.Size([10])
Dimention is : 1
Size is : torch.Size([10])


In [ ]:
# Vector
vector = torch.Tensor([7,7])
print(vector)
print(vector.size())
print(vector.shape)
print(vector.ndim)

tensor([7., 7.])
torch.Size([2])
torch.Size([2])
1


In [ ]:
# Matrix
matrics = torch.Tensor([[[2,3],[4,5]]])

print(matrics)

print("The dimension is : ", matrics.ndim)
print("The shape is : ", matrics.shape)
print("the size is :", matrics.size())
print(matrics[0])
print(matrics[0])

print()

tensor([[[2., 3.],
         [4., 5.]]])
The dimension is :  3
The shape is :  torch.Size([1, 2, 2])
the size is : torch.Size([1, 2, 2])
tensor([[2., 3.],
        [4., 5.]])
tensor([[2., 3.],
        [4., 5.]])



In [ ]:
# Random Tensors
random_tensor = torch.rand(6,7)
print(random_tensor)
print(random_tensor.ndim)
print(random_tensor.shape)
print(random_tensor.size())


tensor([[0.7491, 0.3953, 0.0670, 0.4532, 0.2386, 0.7387, 0.5320],
        [0.6799, 0.3947, 0.7460, 0.2616, 0.3536, 0.7271, 0.8958],
        [0.8084, 0.9422, 0.1394, 0.1529, 0.3319, 0.7747, 0.7920],
        [0.6684, 0.5163, 0.5747, 0.8128, 0.8590, 0.0212, 0.3059],
        [0.8750, 0.4208, 0.8533, 0.2446, 0.0844, 0.2894, 0.1184],
        [0.1172, 0.7809, 0.9680, 0.2146, 0.8594, 0.3828, 0.0528]])
2
torch.Size([6, 7])
torch.Size([6, 7])


In [ ]:
# create similar to image tensor
size = (3, 224, 224)

random_img_tensor = torch.rand(size)
print(random_img_tensor)
print("The dimension is :",random_img_tensor.ndim)
print("The shape is :", random_img_tensor.shape)
print("The size is :",random_img_tensor.size())


tensor([[[0.2573, 0.5379, 0.1187,  ..., 0.2414, 0.3403, 0.8953],
         [0.9370, 0.9636, 0.5245,  ..., 0.8792, 0.3119, 0.0913],
         [0.6883, 0.6449, 0.2750,  ..., 0.1066, 0.4483, 0.3833],
         ...,
         [0.6196, 0.6174, 0.8017,  ..., 0.8312, 0.1074, 0.9517],
         [0.4511, 0.1661, 0.0613,  ..., 0.4938, 0.2829, 0.4840],
         [0.0294, 0.0416, 0.8531,  ..., 0.3567, 0.8949, 0.6628]],

        [[0.2230, 0.9199, 0.8867,  ..., 0.0022, 0.7921, 0.0153],
         [0.8580, 0.9604, 0.8565,  ..., 0.1241, 0.0742, 0.2747],
         [0.3718, 0.5109, 0.6601,  ..., 0.1560, 0.9949, 0.1014],
         ...,
         [0.3899, 0.7395, 0.2946,  ..., 0.2480, 0.5615, 0.9705],
         [0.8799, 0.1227, 0.7456,  ..., 0.7899, 0.0153, 0.7538],
         [0.7290, 0.8570, 0.3041,  ..., 0.6000, 0.2370, 0.1854]],

        [[0.6019, 0.4093, 0.0956,  ..., 0.1054, 0.3891, 0.3913],
         [0.9612, 0.2238, 0.2564,  ..., 0.4513, 0.4918, 0.6679],
         [0.4859, 0.8871, 0.4318,  ..., 0.1201, 0.0415, 0.

In [ ]:
# Create the tensors with 0's
zero_tensors = torch.zeros(3,4)
print(zero_tensors)
print(zero_tensors.ndim)
print(zero_tensors.shape)
print(zero_tensors.size())


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
2
torch.Size([3, 4])
torch.Size([3, 4])


In [ ]:
# Create the tensors with 1's

ones_tensors = torch.ones(2,4,4)
print(ones_tensors)
print(ones_tensors.shape)
print(ones_tensors.ndim)
print(ones_tensors.size())

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
torch.Size([2, 4, 4])
3
torch.Size([2, 4, 4])


In [ ]:
# torch.arange
one_to_ten = torch.arange(start=1, end = 1000, step = 77)
print(one_to_ten)
print(len(one_to_ten))
print(one_to_ten.shape)
print(one_to_ten.ndim)

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])
13
torch.Size([13])
1


In [ ]:
# Using data type

f_tensor = torch.tensor([3.0, 11.0, 20.0, 34.0],
                            dtype=None, # float32, float64, float16
                            device=None, # CPU or Cuda
                            requires_grad=False) # Track the gradients

print(f_tensor)
print(f_tensor.ndim)
print(f_tensor.dtype) # By default the pytorch assigns the float32 to the tensor
print(f_tensor.shape)


tensor([ 3., 11., 20., 34.])
1
torch.float32
torch.Size([4])


In [ ]:

float_16_tensor = torch.tensor([1, 2, 4, 5, 6],
                               dtype = torch.float16,
                               device = None,
                               requires_grad=False)

print(float_16_tensor)
print(float_16_tensor.ndim)

tensor([1., 2., 4., 5., 6.], dtype=torch.float16)
1


In [ ]:
#Converting the data type from one to another

float_32_tensor = torch.tensor([1, 2, 3, 5])
print(float_32_tensor.shape)
print(float_32_tensor.ndim)
print(float_32_tensor.shape)

torch.Size([4])
1
torch.Size([4])


Why random tensors ? : these are important because the way neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers.

`start with random numbers > look at the data > update the random numbers > look at the data > update the random numbers`